### PR TITLE
Added UseForSiteNavigation

### PR DESCRIPTION
**Pull request by PieterVeenstra**
As available within the UI I would like to add UseForSiteNavigation to the schema for a Termset.

### CODE REVIEW

**Comment by wictorwilen** [comment]
Thanks for your contribution, it's a good idea. One immediate feedback is that the attribute can only be used for Site Collection terms not the ones in the default term store. So in effect the attribute is only valid under specific considerations. We will evaluate the pull request.

**Comment by PieterVeenstra** [comment]
Also, there will be a need for specifying navigation specific attributes such as URLs.
________________________________

**Comment by wictorwilen** [comment]
Thanks, and this more points to that this attribute is not sufficient and we should take another more wider approach to this. Ok?

**Comment by PieterVeenstra** [comment]
Agreed.

Sent from my Windows Phone
________________________________

**Comment by PaoloPia** [comment]
Pieter,
Thanks for your contribution, and thanks Wictor for your feedbacks. 
The idea is really good and we can expand on it to find final solution for this need.
I would suggest to use the experimental branch as target for proposed new capabilities. I think we should merge code into master just after some checks, and moreover because we need to keep the XSD schema in the PnP-Sites-Core repo aligned with the master branch of this repo, I would prefer to manage master merges in a more controlled way.
Thus, I hope you don't mind, but I will close this PR and we should move it into the experimental branch. Right?

Thanks,
Paolo

**Comment by PieterVeenstra** [comment]
Ok, that's fine. I'm still new to the PnP update process.

**Pull request closed without merging**
